version: '3'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '3001:3001'
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongo
  mongo:
    container_name: mongo
    image: mongo:3.6-jessie
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
